//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znn_CLicker {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class HotkeySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HotkeySettings defaultInstance = ((HotkeySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HotkeySettings())));
        
        public static HotkeySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("84")]
        public int toggle {
            get {
                return ((int)(this["toggle"]));
            }
            set {
                this["toggle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("112")]
        public int toggleUseLeftMouseButton {
            get {
                return ((int)(this["toggleUseLeftMouseButton"]));
            }
            set {
                this["toggleUseLeftMouseButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("113")]
        public int toggleUseRightMouseButton {
            get {
                return ((int)(this["toggleUseRightMouseButton"]));
            }
            set {
                this["toggleUseRightMouseButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("114")]
        public int toggleUseMiddleMouseButton {
            get {
                return ((int)(this["toggleUseMiddleMouseButton"]));
            }
            set {
                this["toggleUseMiddleMouseButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("82")]
        public int toggleUseRandomMultiplier {
            get {
                return ((int)(this["toggleUseRandomMultiplier"]));
            }
            set {
                this["toggleUseRandomMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("68")]
        public int toggleUseDelay {
            get {
                return ((int)(this["toggleUseDelay"]));
            }
            set {
                this["toggleUseDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int toggleUseRandomDelay {
            get {
                return ((int)(this["toggleUseRandomDelay"]));
            }
            set {
                this["toggleUseRandomDelay"] = value;
            }
        }
    }
}
