//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Znn_CLicker {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class ThemeSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ThemeSettings defaultInstance = ((ThemeSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ThemeSettings())));
        
        public static ThemeSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useDarkMode {
            get {
                return ((bool)(this["useDarkMode"]));
            }
            set {
                this["useDarkMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue700")]
        public global::MaterialSkin.Primary Primary1 {
            get {
                return ((global::MaterialSkin.Primary)(this["Primary1"]));
            }
            set {
                this["Primary1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue900")]
        public global::MaterialSkin.Primary Primary2 {
            get {
                return ((global::MaterialSkin.Primary)(this["Primary2"]));
            }
            set {
                this["Primary2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue500")]
        public global::MaterialSkin.Primary Primary3 {
            get {
                return ((global::MaterialSkin.Primary)(this["Primary3"]));
            }
            set {
                this["Primary3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange100")]
        public global::MaterialSkin.Accent Accent1 {
            get {
                return ((global::MaterialSkin.Accent)(this["Accent1"]));
            }
            set {
                this["Accent1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WHITE")]
        public global::MaterialSkin.TextShade TextShade {
            get {
                return ((global::MaterialSkin.TextShade)(this["TextShade"]));
            }
            set {
                this["TextShade"] = value;
            }
        }
    }
}
